# Generated by Django 3.1.2 on 2021-06-20 20:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(max_length=30)),
                ('abbreviation', models.CharField(blank=True, max_length=10, unique=True)),
                ('symbol', models.CharField(blank=True, max_length=3, unique=True)),
                ('category', models.CharField(choices=[('HISTORY', 'Historical'), ('PROPHETS', 'Prophetic'), ('POETIC', 'Poetic and Other Writings'), ('PAUL', "Paul's Letters"), ('LETTERS', 'Letters from Others')], max_length=12)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
