# Generated by Django 3.1.2 on 2021-06-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0004_auto_20210620_2118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='canonical_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='book',
            name='chronological_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
