# Generated by Django 3.1.2 on 2021-06-21 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0005_auto_20210620_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='book',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='notes.book'),
        ),
        migrations.AddField(
            model_name='note',
            name='reference',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='note',
            name='sort_order',
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='note',
            name='title',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
